{ pkgs, ... }:
{
  # Desktop profile: full runtime set for Electron/GTK/Qt/multimedia apps
  programs.nix-ld = {
    dev.enable = true;
    libraries = with pkgs; [
      alsa-lib
      atk
      at-spi2-atk
      at-spi2-core
      cairo
      cups
      dbus
      dbus-glib
      desktop-file-utils
      flac
      fontconfig
      freeglut
      freetype
      fribidi
      fuse
      fuse3
      gdk-pixbuf
      gtk3
      glew110
      gst_all_1.gst-plugins-base
      gst_all_1.gst-plugins-ugly
      gst_all_1.gstreamer
      harfbuzz
      keyutils.lib
      libcaca
      libcanberra
      libclang.lib
      libdbusmenu
      libdrm
      libGL
      libGLU
      libjack2
      libjpeg
      libmikmod
      libogg
      libpng12
      libpulseaudio
      librsvg
      libsamplerate
      libthai
      libtheora
      libtiff
      libudev0-shim
      libusb1
      libvdpau
      libvorbis
      libvpx
      libxkbcommon
      mesa
      pango
      pixman
      python3
      SDL
      SDL2
      SDL2_image
      SDL2_mixer
      SDL2_ttf
      SDL_image
      SDL_mixer
      SDL_ttf
      speex
      tbb
      vulkan-loader
      wayland
      xorg.libICE
      xorg.libpciaccess
      xorg.libSM
      xorg.libX11
      xorg.libxcb
      xorg.libXcomposite
      xorg.libXcursor
      xorg.libXdamage
      xorg.libXext
      xorg.libXfixes
      xorg.libXft
      xorg.libXi
      xorg.libXinerama
      xorg.libXmu
      xorg.libXrandr
      xorg.libXrender
      xorg.libXScrnSaver
      xorg.libXt
      xorg.libXtst
      xorg.libXxf86vm
      xorg.xcbutil
      xorg.xcbutilimage
      xorg.xcbutilkeysyms
      xorg.xcbutilrenderutil
      xorg.xcbutilwm
      xorg.xkeyboardconfig
    ];
  };
}
